### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by MarioGK** [MihaZupan/LLRP#1]
Hi, it seems like an interesting project, i tried running it locally and it seems to not be working, could you shed me some light where to search or debug?

**Comment by MihaZupan** [comment]
What do you mean by not working? Note that the prototype only supports basic HTTP 1.1 GET requests. By default it will proxy everything to [`http://localhost:8081`](https://github.com/MihaZupan/LLRP/blob/42872002880f58c756ba8e8a3363f06afaaecd3f/LLRP/Program.cs#L142)

**Comment by MarioGK** [comment]
Google Chrome was redirecting to HTTPS my bad, it is working, it is an amazing project good job, learned a lot while reading the code.
